# This rule is not used by the project customsecret itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to api.example.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: customsecret
    app.kubernetes.io/managed-by: kustomize
  name: customsecret-viewer-role
rules:
- apiGroups:
  - api.example.com
  resources:
  - customsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.example.com
  resources:
  - customsecrets/status
  verbs:
  - get
