apiVersion: api.example.com/v1alpha1
kind: CustomSecret
metadata:
  labels:
    app.kubernetes.io/name: customsecret
    app.kubernetes.io/managed-by: kustomize
  name: customsecret-sample
spec:
  type: "basic-auth"
  username: "admin"
  passwordLen: 40
  rotationPeriod: 90
